### ISSUE TITLE
How to get message ID !?

### ISSUE THREAD

**Issue by Arosado101** [yyyyyyyan/onesecmail#1]
I see in your documentation that one can retrieve the messages with message ID, but I don't see how to retrieve message ID's from "address". Normally what I wanted was to ignore the rest of the message and go for the len [0] and to also have it show the HTML body or what would be the message body. I would not make sense to just have the subject.

**Comment by yyyyyyyan** [comment]
Hi @Arosado101! Sorry for taking so long to respond. 1secmail's API only return the message ID through the `getMessages` endpoint, and the user would need to use the `readMessage` endpoint with the returned message ID to get the message data. Our package does all that through the `OneSecMail.get_messages()` method, which returns a list of messages (with the complete message data). Internally, `get_messages()` use the `get_message()` method in order to retrieve the complete message data, but you'd need to know the message ID beforehand to make use of the `get_message()` method directly.

**Comment by GlobalBritain** [comment]
This is how 

```
from onesecmail import OneSecMail
# Creates a mailbox using a pre-determined address:
mailbox = OneSecMail.from_address(<email address you want to get message from>)
mailbox.get_messages()[0].id
```

The messages are created as a list, so which the message you want the id for, you get from the list position.
